### ISSUE TITLE
好像没有起作用

### ISSUE THREAD

**Issue by tanxiaolong** [mircoteam/mailtemplate#1]
我就是安装README.MD里的操作执行的，但也没有收到邮件警报。不知道您是不是哪里遗漏了没说。

**Comment by mircoteam** [comment]
你好，非常高兴您使用本插件。

本插件是基于原生监控系统监控邮件已经可以使用的情况下，进行插件化的增强。
首先保证原生的邮件告警是可以使用。
这样再进行插件化增强。
